admin:
- 0
alarmclockgroup:
- 0
blacklist:
- 0
botname: ''
commandpre: ''
mutegrouplist:
- 0
settings:
  autogetpaipu: true
  autowelcome: true
welcomeinfo:
- ª∂”≠%ps%º”»Î»∫¡ƒ%gn%
whitelist:
- 0
