adapter:
  host: localhost
  port: 17280
  verify_key: NekoRabi
admin:
- 0
alarmclockgroup:
- 0
blacklist:
- 0
botconfig:
  botname: ""
  qq: 123456
commandpre: ''
mutegrouplist:
- 0
searchfrequency: 6
settings:
  autogetpaipu: true
  autowelcome: true
  r18talk: true
  setu: false
welcomeinfo:
- 欢迎%ps%加入%gn%
whitelist:
- 0
