admin:
- 0
alarmclockgroup:
- 0
blacklist:
- 0
botconfig:
  botname: ""
  host: localhost
  port: 17280
  qq: 123456
  verify_key: NekoRabi
commandpre: ''
searchfrequency: 3
mutegrouplist:
- 0
settings:
  autogetpaipu: true
  autowelcome: true
  r18talk: true
welcomeinfo:
- 欢迎%ps%加入%gn%
whitelist:
- 0
