from plugin.preinit import *
from utils import *
from plugin.jupai import *
from plugin.LeisurePlugin import *
from plugin.Petpet import *
from plugin.KissKiss import *
from plugin.MajSoulInfo import *
from plugin.Setu import *
from plugin.Remake import *
from plugin.TenHouPlugin import *
from plugin.ImgOperation import *
from plugin.draw_wife import *
from plugin.paili_analysis import *
from plugin.prank_on_groupmember import *
