# 指令正则  ^{commandpre}addadmin\s*(\d+)\s*$
# 只能修改 ^{commandpre}" 后面的部分，会自动拼接指令前缀
# 注意: 冒号后面要有空格
# 请严格保持括号顺序,不要增加，也不要减少，修改顺序和变更数量会导致程序出错
sys:
  ping: ping\s*$
  help: ([hH][eE][lL][pP]|帮助)\s*$
  addadmin: addadmin\s*(\d+)\s*$
  deladmin: deladmin\s*(\d+)\s*$
  sendmsgtogroup: stext::\s*([0-9]+)\s*(\S+)\s*$
  getbotinfo: getinfo\s*$
  silence_all: silence\s*(\w+)\s*$
  silence_group: silence\s*(\w+)\s*$
  repeat: norepeat\s*(\w+)\s*$
  addwhitelist: addwhitelist\s*([0-9]+)\s*$
  delwhitelist: delwhitelist\s*([0-9]+)\s*$
  addblacklist: addblacklist\s*([0-9]+)\s*$
  delblacklist: delblacklist\s*([0-9]+)\s*$
  log: log\s*(\w+)?\s*(\d+)\s*$
  tell_master: \s*转告主人\s*(\S+)$

  signin: \s*签到\s*$
  getscore: \s*获取当前积分\s*$
  tarot: \s*(\d)?张?(([tT][Aa][Rr][oO][Tt])|(塔罗牌))
  getmytarot: \s*我的塔罗牌

setu:
  enable: (open|enable|开启)\s*(涩图|色图|setu)\s*$
  disable: (close|disable|关闭)\s*(涩图|色图|setu)\s*$
  getsetu1: (色图|涩图|setu)\s*(\S+)?\s*$
  getsetu2: 来(\d)*[张份点]?(\S+)*\s*(的)?\s*[色涩涉]图\s*$

tenhou:
  thpt: (thpt|天凤pt|天凤分数)\s*(\S+)\s*(\S+)?\s*$
  addwatch: (thadd|天凤添加关注)\s*(\S+)\s*$
  delwatch: (thdel|天凤删除关注)\s*(\S+)\s*$
  getwatch: (thgetwatch|天凤获取本群关注)\s*$
  clearwatch: (thclearwatch|天凤清除本群关注)\s*$


  tagon:  (thtagon|天凤添加标记)\s*(\S+)\s*(\S+)\s*$
  tagoff: (thtagoff|天凤删除标记)\s*(\S+)\s*(\S+)?\s*$
  taglist: (qhtaglist)\s*(\S+)?\s*$

jupai:
  jupai: 举牌\s*(\S+)\s*$

reply:
  jida: ([\w\d]+)鸡打\s*\.
  wochao: 我超(\w+)\s*\.
  kisskiss: (亲|亲亲)\s*@?(\w+)?\s*
  touchhead: (摸|摸摸|摸头)\s*@?(\w+)?\s*$

imgoperation:
  bw: bw\s*(\S+)\s*$

remake:
  remake: (重开|remake)\s*(\d+)?\s*(\w+)?\s*$

sendvoice:
  sendvoice: \s*说[:：]?\s*(.+)\s*$
  sendgroupvoice: \s*在(\d+)说[:：]?\s*(.+)\s*$
