addwatch: (qhadd|雀魂添加关注)\s*(\S+)\s*$
changlink: qhfreshlink\s*$
clearwatch: (qhclearwatch|雀魂清除本群关注)\s*$
cleargroupwatch: qhcleargroupwatch\s*(\d+)$
dbupdate: qhfreshdb\s*$
delwatch: (qhdel|雀魂删除关注)\s*(\S+)\s*$
disable: (qhdisable)\s*(\w+)\s*$
enable: (qhenable)\s*(\w+)\s*$
getmyqhsl: (getmyqhsl|我的雀魂十连)\s*$
getwatch: (qhgetwatch|雀魂获取本群关注)\s*$
qhinfo: (qhinfo|雀魂玩家详情)\s*(\S+)\s*(\d+)\s*(\w+)*\s*(\w+)*\s*$
qhpaipu: (qhpaipu|雀魂最近对局)\s*(\S+)\s*([34])*\s*([0-9]+)?\s*$
qhpt: (qhpt|雀魂分数|雀魂pt)\s*(\S+)\s*([34])?\s*([0-9]+)?\s*$
qhsl: (qhsl|雀魂十连)\s*(\w+)*\s*$
qhyb: (qhyb|雀魂月报)\s*(\S+)\s*([34])?\s*([0-9]{4})?[-]?([0-9]{1,2})?\s*$
taglist: (qhtaglist)\s*(\S+)?\s*$
tagoff: (qhtagoff|雀魂删除标记)\s*(\S+)\s*(\S+)?\s*$
tagon: (qhtagon|雀魂添加标记)\s*(\S+)\s*(\S+)\s*$
tagopeartion: (qhtag)\s*(\S+)\s*(\S+)\s*(\S*)?\s*
