qhsettings: # 是否启用
  qhpt: true
  qhinfo: true
  qhsl: true
  qhyb: true
  qhpaipu: true
  autoquery: true
  disptgroup: # 在某群禁用 qhpt
    - 0
  disinfogroup:
    - 0
  disslgroup:
    - 0
  disybgroup:
    - 0
  dispaipugroup:
    - 0