endboardcast:
  format: "牌谱链接:%paipuurl% <br>开始时间:%startTime% <br>结束时间:%endTime% <br>对局玩家:%players%"
  head: "检测到新的对局:<br>"
  sort: false
qhinfo:
  format: '%k% : %v% <br>'
qhpaipu:
  footer: "总PT收支:%ptupdate%"
  format: "牌谱链接:%paipuurl% <br>开始时间:%startTime% <br>结束时间:%endTime% <br>对局玩家:%players%<br>"
  head: '玩家%playername%最近%counts%场对局如下:'
qhpt: ' 玩家名: %playername%<br>三麻: %pl3% <br>四麻: %pl4% '
qhsl:
  maxdraw: 3
qhyb:
  infomsg: '立直率: %立直率%<br> 副露率: %副露率%<br> 和牌率: %和牌率%<br> 放铳率: %放铳率%<br> 默听率: %默听率%<br>
    平均打点: %平均打点%<br> 平均铳点: %平均铳点%'
  pl3: "玩家%playername%在%Y年%m月共进行了%counts%场对局,共计%1st%次①位,%2nd%次②位,%3rd%次③位,%4th%次④位,平均顺位:%averank%,%flycount%,PT得失:%ptchange%<br>"
  pl4: "玩家%playername%在%Y年%m月共进行了%counts%场对局,共计%1st%次①位,%2nd%次②位,%3rd%次③位,平均顺位:%averank%,%flycount%,PT得失:%ptchange%<br>"
